services:
  zookeeper-local:
    container_name: zookeeper-local
    image: confluentinc/cp-zookeeper:7.0.0
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      my_network:
        aliases:
          - zookeeper-local-host

  kafka-local:
    container_name: kafka-local
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - 9093:9093
      - 9092:9092
    environment:
      KAFKA_LISTENERS: LOCALHOST://0.0.0.0:9093, DOCKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LOCALHOST://localhost:9093, DOCKER://kafka-local-host:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCALHOST:PLAINTEXT, DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-local:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=false,kafka.producer.async.DefaultEventHandler=false,state.change.logger=false"
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper-local
    networks:
      my_network:
        aliases:
          - kafka-local-host

  kafka-ui-local:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-local
    ports:
      - "8080:8080"
    depends_on:
      - kafka-local
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-local-host:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-local-host:2181
    networks:
      my_network:
        aliases:
          - kafka_ui


networks:
  my_network:
    name: my_network
    external: true
